version: '3.8'

services:
  springboot-server:
    container_name: springboot-server-dev
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=jdbc:postgresql://postgres_server/spring_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
    volumes:
      - ./:/app

  postgres_server:
    container_name: postgres_server
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring_demo
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: